apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-scheduler-cluster-role
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["list", "apply", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-scheduler-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: job-scheduler-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-scheduler-cluster-role
  apiGroup: rbac.authorization.k8s.io
