apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-scheduler-server
  template:
    metadata:
      labels:
        app: job-scheduler-server
    spec:
      containers:
      - name: job-scheduler-deployment
        image: panagiotisptr/job-scheduler
        ports:
          - containerPort: 80
        env:
          - name: CONFIG_URL
            valueFrom:
              configMapKeyRef:
                name: job-scheduler-config
                key: config_url
---
apiVersion: v1
kind: Service
metadata:
  name: job-scheduler-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: job-scheduler-server
